### PR TITLE
change description flag to display-name in create-project

### LINKED ISSUE #41: Project description is applied to `display-name` annotation instead of `description`
**Describe the bug**
Project description is applied to `display-name` annotation instead of `description`

**Steps To Reproduce**
1. Run `opfcli create-project -r ../apps testproject testgroup -q x-small -d "My test description."`
2. Check namespace manifests
```yaml
annotations:
        openshift.io/display-name: project-description
```

**Expected behavior**
description should be applied to the `description` annotation instead of `display-name` 
```yaml
annotations:
        openshift.io/description: project-description
```
**Workaround (if any)**
Manually change the manifests

### PR DESCRIPTION
**Pull request by 4n4nd**
Resolves https://github.com/operate-first/opfcli/issues/41

### CODE REVIEW

**Comment by tumido** [comment]
Let's resolve the discussion at https://github.com/operate-first/opfcli/issues/41 first.

**Comment by 4n4nd** [comment]
@tumido updated the PR according to [your comment](https://github.com/operate-first/opfcli/issues/41#issuecomment-862180119)

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by larsks — APPROVED** [review]

**Pull request merged**
