### PR TITLE
Run Go linters and unit tests as pre-commit hooks

### LINKED ISSUE #3: Update precommit configuration for Go source
We should update the pre-commit configuration using e.g. https://github.com/dnephin/pre-commit-golang/. We'd probably want something like:

```
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: golangci-lint
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
```

This would require adding some tools to our CI image

### PR DESCRIPTION
**Pull request by larsks**
This updates the pre-commit configuration to run Go linters and unit
tests as pre-commit hooks. This requires an updated CI image with the
necessary Go tooling.

Note that image location will probably need to be udpated before we
merge this change.

Closes #3

### CODE REVIEW

**Comment by larsks** [comment]
This requires an updated CI image, but I don't know exactly how prow runs the CI images, so need to sort that out first.

**Review by tumido — APPROVED** [review]
/approve

**Comment by larsks** [comment]
This has been superseded by more recent work on the repository (that
will show up in a subsequent pull request).

**Pull request closed without merging**
