### PR TITLE
update the prow resource limits

### PR DESCRIPTION
**Pull request by harshad16**
update the prow resource limits
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: https://github.com/thoth-station/thoth-application/issues/1332

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
@harshad16 is there a reason why is this PR different from the rest of the PRs in this series? The others set both `limits` and `requests` while this PR just removes it. I know those were the 2 solution you've offered - any reason to choose this solution here and a different solution for the rest of the repos?

**Comment by harshad16** [comment]
> is there a reason why is this PR different from the rest of the PRs in this series? The others set both `limits` and `requests` while this PR just removes it. I know those were the 2 solution you've offered - any reason to choose this solution here and a different solution for the rest of the repos?

as the repo was fairly new default value seems okay for this repo. we can upgrade once we face any issue with other newer limits, till than it felt default was good enough.

**Review by tumido — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
