### PR TITLE
feat: Enable cobra completion

### LINKED ISSUE #35: Offer completion for shells
SSIA

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/opfcli/issues/35

Do we need tests for this? Is there anything to test?

### CODE REVIEW

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
I see that dynamic completion is possible: https://github.com/spf13/cobra/blob/master/shell_completions.md#dynamic-completion-of-nouns 

Was there a reason why we're requiring to import completion before execution, and not dynamically calculating them?

**Comment by tumido** [comment]
> Was there a reason why we're requiring to import completion before execution, and not dynamically calculating them?
@HumairAK 

No reason. This was just simpler at this point... We don't really have any dynamic fields as of now, do we? I think that once we really do have them, we can change this... I don't mind.. I just went the simpler path... We can iterate over it again any time.

**Comment by HumairAK** [comment]
sounds good to me! 
/lgtm
/approve

**Pull request merged**
