### PR TITLE
Implement kafka-ca-crt command

### PR DESCRIPTION
**Pull request by larsks**
Add the `kafka-ca-crt` command to `opfcli`.  It looks like this:

```
$ opfcli kafka-ca-crt
-----BEGIN CERTIFICATE-----
MIIDLTCCAhWgAwIBAgIJANuSIZhiRRcJMA0GCSqGSIb3DQEBCwUAMC0xEzARBgNV
BAoMCmlvLnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwHhcNMjEwNDA2
MjA0MjQxWhcNMjIwNDA2MjA0MjQxWjAtMRMwEQYDVQQKDAppby5zdHJpbXppMRYw
FAYDVQQDDA1jbHVzdGVyLWNhIHYwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAweEk7lz63ntiQL44RW3mfVbCGWAImrz3WUdAnBhBC70fMu5SVxtBlD7/
Ycv8VB4A+IF9JXaQdXgCY8sqdPcM+OTRw7Ye7HhAPxVpDSCkD7hngq0jxll/f+5n
kpa6o6CTcM4eeGmcgrhY7ahwSu4s5Ps8jHzSKOSnfnr2pzyRIwq0SNB6DATxza2C
To8VA3EgPXyA5XQNY6HCieG29R5yxF3ho7eMQvbdJ/iAedJUN2vp5ZYG3h3/DrqO
G/hqmo+X8LaTF54xwAXeZXAMcn3zYlD/uIzwlCjXdeES/6cImD6qdB5q9kIEAiXR
KXFszCfpCbFSRK9VM3t1X2giLq9x8wIDAQABo1AwTjAdBgNVHQ4EFgQUVZURVDGz
FkbRkeGMiPw0RtqXJCwwHwYDVR0jBBgwFoAUVZURVDGzFkbRkeGMiPw0RtqXJCww
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAR2gPmy070tulw8hRKTxQ
aRwsbytCek4PJT/eLJtenFLB8SnCqeMPYlzx1LeMQzY3VEgJe4gILiIp9+DUwhQT
CaTstSclC3aY2Jmut89K2iO8DKmHZhP2W5xw0/PFEv9i28mMwdvFdEg6iGbkgKWr
W8JZe4HjFOajqeo9YDF9GNr9Vt9z9yOxIwB1ok1aCaaDnSQxobuQQuOF5FUyfCRw
5aPN30jMNxRsvwEm3vAUKLfHHyLVH1Su9sXImruWlxXdJm5Bl3niMd1kwIsX4yvv
OiSLN1ya4wqnF1Wy7KnmFwbx8rbwmLH3TwLQC3F4RCuvpahBK1+RrrzPwbF/Vw4E
cw==
-----END CERTIFICATE-----
```

### CODE REVIEW

**Comment by larsks** [comment]
I picked this because it's a very simple and gives us a chance to discuss how to implement commands that interact with k8s.  I have several questions:

- Does this seem like a reasonable approach to hande getting a k8s client object in general?
- Any thoughts on how to test this? I haven't tried mocking anything with Go before, so if you have some idea where to start, I'm all ears.
- Is this a reasonable solution to #31 specifically?

**Comment by tumido** [comment]
Just curious and brainstorming functionality now. Assuming this works only if the user is logged in to the cluster and has access to the said namespace and can get secrets, how much is this feature useful? It seems it can be used by operate first maintainers anyways, correct? If we want to share the cert with all the users I think it would make sense just to store it in plain text in the repo, wouldn't it?

**Comment by larsks** [comment]
It turns out the reason there was a request for this command in https://github.com/operate-first/opfcli/issues/31 was due to some misunderstanding about how SSL works. We could in fact just publish the certificate in our documentation. The more interesting aspect of this PR is providing a framework for interacting with the Kubernetes API, so maybe we separate that out into a new PR and close this one.

**Comment by tumido** [comment]
Yeah, I understand the learning exercise in this, I appreciate it a lot :slightly_smiling_face:

My comment was focusing on the "get me the cert" functionality which doesn't seem much useful right now - but maybe there's a way to make it useful, who knows. I'm open to ideas :slightly_smiling_face: Let's define the feature in the issue properly then.

**Pull request closed without merging**
